builds:
  - 
    binary: skeema
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
archives:
  -
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}mac{{ else }}{{ .Os }}{{ end }}_
      {{- .Arch }}
checksum:
  name_template: '{{ .ProjectName }}_checksums_{{ .Version }}.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '(?i)^docs:'
    - '(?i)^help'
    - '(?i)^internal'
    - '(?i)^readme:'
    - '(?i)^goreleaser:'
nfpms:
  -
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage:  https://www.skeema.io
    description: Schema management CLI for MySQL
    maintainer: Evan Elias <evan@skeema.net>
    license: Apache 2.0
    vendor: Skeema LLC
    formats:
      - deb
      - rpm
      - apk
brews:
  -
    name: skeema
    tap:
      owner: skeema
      name: homebrew-tap
    commit_author:
      name: goreleaser
      email: bot@skeema.net
    folder: Formula
    homepage: https://www.skeema.io/
    description: "Skeema is a tool for managing MySQL tables and schema changes in a declarative fashion using pure SQL."
