version: 2
builds:
  - 
    binary: skeema
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{.CommitTimestamp}}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}}
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
archives:
  -
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}mac{{ else }}{{ .Os }}{{ end }}_
      {{- .Arch }}
    format_overrides:
      - goos: darwin
        formats: ["zip", "tar.gz"]
checksum:
  name_template: '{{ .ProjectName }}_checksums_{{ .Version }}.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^help'
    - '^internal'
    - '^chore:'
    - '^test'
    - '^ci:'
    - '^modules:'
    - '^dependencies:'
    - '^version bump'
nfpms:
  -
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage:  https://www.skeema.io
    description: Schema management CLI for MySQL
    maintainer: Evan Elias <evan@skeema.net>
    license: Apache 2.0
    vendor: Skeema LLC
    formats:
      - deb
      - rpm
      - apk
brews:
  -
    name: skeema
    repository:
      owner: skeema
      name: homebrew-tap
    commit_author:
      name: goreleaser
      email: bot@skeema.net
    directory: Formula
    homepage: https://www.skeema.io/
    description: "Skeema is a tool for managing MySQL tables and schema changes in a declarative fashion using pure SQL."
