builds:
- binary: skeema
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GOFLAGS=-mod=vendor
  goos:
    - linux
    - darwin
  goarch:
    - amd64
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: mac
      linux: linux
checksum:
  name_template: '{{ .ProjectName }}_checksums_{{ .Version }}.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '(?i)^docs:'
    - '(?i)^help'
    - '(?i)^internal'
    - '(?i)^readme:'
    - '(?i)^goreleaser:'
nfpms:
  -
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage:  https://skeema.io
    description: Schema management CLI for MySQL
    maintainer: Evan Elias <evan@skeema.net>
    license: Apache 2.0
    vendor: Skeema LLC
    formats:
    - deb
    - rpm
brews:
 -
   name: skeema

   tap:
     owner: skeema
     name: homebrew-tap

   folder: Formula
   homepage: https://www.skeema.io/
   description: "Skeema is a tool for managing MySQL tables and schema changes in a declarative fashion using pure SQL."
